defmodule AWSEventStream.Fixtures do
  @moduledoc false
  alias AWSEventStream.{Header, Message}

  @dir Path.join(__DIR__, "../fixtures")

  # Self-encoded regression locks that pin the wire format of known messages.
  # The hex bytes were generated by running AWSEventStream.Encoder.encode/1 against
  # the corresponding Message struct and freezing the output. They are NOT transcribed
  # from an external source — they lock in the codec's own wire format.
  #
  # Externally-sourced vectors from aws-sdk-go-v2/botocore (to verify interoperability
  # with AWS SDKs) are future watcher work tracked in MIM-43.
  def golden_vectors do
    [
      %{
        name: "single string header, empty payload",
        hex:
          "0000003100000021b50a5e010d3a636f6e74656e742d747970650700106170706c69636174696f6e2f6a736f6ea4a43b08",
        message: %Message{
          headers: [%Header{name: ":content-type", type: :string, value: "application/json"}],
          payload: ""
        }
      },
      %{
        name: "mixed header types (string + integer) with JSON payload",
        hex:
          "0000006b0000004b6ace012d0b3a6576656e742d74797065070007636f6e74656e740d3a636f6e74656e742d747970650700106170706c69636174696f6e2f6a736f6e0e782d73657175656e63652d6e756d040000002a7b2274657874223a2268656c6c6f227dc429b2cf",
        message: %Message{
          headers: [
            %Header{name: ":event-type", type: :string, value: "content"},
            %Header{name: ":content-type", type: :string, value: "application/json"},
            %Header{name: "x-sequence-num", type: :integer, value: 42}
          ],
          payload: ~s({"text":"hello"})
        }
      }
    ]
  end

  def bedrock_exception_frame do
    @dir |> Path.join("bedrock_exception.bin") |> File.read!()
  end
end
